# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b89c67719996851c8e5c57709a8d81a89145b45372b39687fe61c1f7df8e27f72572c115886f42530eb5c5e4ade5e83e628556cfe1aad86ca187b00c14b2f422

test:
  secret_key_base: d506cb67fbff2eb58204ea83ba029aa9b192b49f3bd6c85e0b2e02b0844ac6cd93cfcf37f9657a9844741f8fc2cdf315065237f01be266c637073e5b1c1b91d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
